# This file is for sensitive heat data - eg: passwords, etc.
# To use it, make a copy of this file and add the required parameters.
# Then when launching the instance pass it in via the command line - eg:
#   heat stack-create --template-file=IdeaProjects/HubZeroPuppet/heat/hubzero.yaml \
#                     --environment-file=IdeaProjects/HubZeroPuppet/heat/environment.yaml \
#                     hubzero_test
parameters:
  hub_zero_version: # 1.1 | 1.2 | 1.3 | 1.3.1
  email: # a valid email address to notify when the installation is complete.
  hostname: # a valid fully qualified hostname, eg: hubzero.v3.edu.au
  nagiosserver : # the nagios host that will be monitoring this server.
  key: # the key pair to use to launch the vm
  tenancy_name: # OS_TENANT_NAME in the downloaded NeCTAR project resource file
  nectar_user_id: # OS_USERNAME in the downloaded NeCTAR project resource file
  swift_password: # OS_PASSWORD in the downloaded NeCTAR project resource file
  pgp_passphraze: # The password used to access Swift backups.