heat_template_version: 2013-05-23

description: A template to initiate the installation of hubZero 1.1 on an instance in the NeCTAR cloud

# Because this file uses the get_file command, it can only be launched by the command line client
# eg:
#   heat stack-create --template-file=IdeaProjects/HubZeroPuppet/heat/hubzero.yaml \
#                     --environment-file=IdeaProjects/HubZeroPuppet/heat/environment.yaml \
#                     hubzero_test

parameters:
  image:
    type: string
    label: Image name or ID
    description: A member of the Debian GNU/Linux 6.x family
    default: NeCTAR Debian 6 x86_64 (Squeeze)

  flavor:
    type: string
    label: Flavor
    description: Type (size) of the instance to be created.
    default: m1.small
    constraints:
      - allowed_values: [m1.small, m1.medium, m1.large, m1.xlarge, m1.xxlarge]
        description: Must be a valid NeCTAR flavour.

  key:
    type: string
    label: Key Name
    description: Name of an existing key pair to enable SSH access to the instance.
    default: nectar_dev

  my_sql_root_password:
    type: string
    label: MySql Root Password
    description: The password that gives absolute access to the database.
    hidden: true
    constraints: # update the environment_template.yaml if changing the constraints...
      - length: { min: 6, max: 16 }
        description: The password length must be between 6 and 16 characters long.
      - allowed_pattern: "[a-zA-Z0-9]+"
        description: The password must consist of characters and numbers only.
      - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
        description: The password must start with an uppercase character.

  slapd_root_password:
    type: string
    label: LDAP Server Root Password
    description: The password that gives absolute access to the LDAP service.
    hidden: true
    constraints: # update the environment_template.yaml if changing the constraints...
      - length: { min: 6, max: 16 }
        description: The password length must be between 6 and 16 characters long.
      - allowed_pattern: "[a-zA-Z0-9]+"
        description: The password must consist of characters and numbers only.
      - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
        description: The password must start with an uppercase character.

  hub_zero_version:
    type: string
    label: HubZero Version
    description: The version of HubZero to install.
    default: 1_1
    constraints:
      - allowed_values: [1_1, 1_2, 1_3]
        description: Will install either 1.1.0, 1.2.2, or 1.3.0

resources:
  hubZero_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      user_data:
        str_replace:
          params:
            __my_sql_root_password: { get_param: my_sql_root_password }
            __slapd_root_password: { get_param: slapd_root_password }
            __hub_zero_version: {get_param: hub_zero_version }
          template:
            get_file: https://raw.githubusercontent.com/MartinPaulo/puppet_hub_zero/master/puppet/scripts/bootstrap.sh
      user_data_format: RAW


outputs:
  instance_name:
    description: The name of the instance
    value: { get_attr: [hubZero_instance, name] } # TODO: is not returning anything?

  instance_ip:
    description: The IP address of the instance
    value: { get_attr: [hubZero_instance, first_address] }